### ISSUE TITLE
T/S diagrams

### ISSUE THREAD

**Issue by adele157** [pedrocol/basal_mom5-collaborative-project#30]
Make regional T/S diagrams. Is the basal melt simulation closer to obs? How much ISW do we get?

The issue on this using the old simulations is [here](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/4).

**Comment by claireyung** [comment]
Pedro made this Amery T-S diagram (just putting this here so I can reference it)

@bkgf said at last meeting 17/11 that it looks improved from both control and previous heat balance formulation of parameterisation

getting some ice shelf water below freezing point too!
<img width="823" alt="Screenshot 2022-11-23 at 11 28 01 am" src="https://user-images.githubusercontent.com/61528379/203447585-fe19af94-45dc-4159-aac9-40547c281f0a.png">

**Comment by hrsdawson** [comment]
Okay here's some other regional T-S plots from the regions in the map (minus Amundsen which is shown above). Certainly getting more ice shelf water in the Gade formulation. 

<img width="806" alt="Screen Shot 2022-11-23 at 3 27 17 pm" src="https://user-images.githubusercontent.com/62230733/203469293-1555b768-933b-46f0-b4ad-fe8cb6062e4c.png">
. Certainly getting more ice shelf water, particularly in Weddell Sea. 
<img width="1333" alt="Screen Shot 2022-11-23 at 3 21 37 pm" src="https://user-images.githubusercontent.com/62230733/203469307-6bfd9391-55af-4cb0-9023-6243e84d24c0.png">
<img width="1349" alt="Screen Shot 2022-11-23 at 3 28 11 pm" src="https://user-images.githubusercontent.com/62230733/203469412-ddd08113-dcb9-4a63-a43d-d94f25479e72.png">

**Comment by adele157** [comment]
Yeah, wow, check out the Weddell Sea ISW! Cool! Do we know how this compares to obs?

**Comment by hrsdawson** [comment]
Here's a limited comparison with mooring observations from in front of the Dotson Ice Shelf (https://www.nature.com/articles/s41467-022-28751-5). Gade and heat balance formulations have better salinity spread than the control in this location, plus the Gade formulation also looks to have less temperature bias than the previous heat balance formulation. 

![Slide1](https://user-images.githubusercontent.com/62230733/203469711-60bc8d27-b871-41ab-90e5-c64bc6e5b5a1.png)

![Slide2](https://user-images.githubusercontent.com/62230733/203469824-c306519a-bbe3-4fe2-b67d-a48310902015.png)

**Comment by hrsdawson** [comment]
> Yeah, wow, check out the Weddell Sea ISW! Cool! Do we know how this compares to obs?

@adele157 I'm now looking at a comparison to obs from different regions that @mmr0 posted in another issue (https://doi.org/10.1029/2018JC014907). This has some T-S plots from the Weddell (top left) though the detail isn't that that clear. Will update with the comparison figs shortly. Do you know of any other good obs data from the Weddell?


<img width="718" alt="Screen Shot 2022-11-23 at 2 51 11 pm" src="https://user-images.githubusercontent.com/62230733/203470090-b085e20a-226c-47fc-96ca-32451b4973e8.png">

**Comment by hrsdawson** [comment]
Here's the above plot using 3rd year of the heat balance and Gade line simulations. The figure for the control is available in [this notebook.](https://github.com/pedrocol/basal_mom5-collaborative-project/blob/main/notebooks/TS_diag/TS_obs_comparison.ipynb). The paper classifies the seal data used in the obs as 'near-ice-shelf' (NIS) and 'distant-from-ice-shelf' (DIS) based on whether profiles are within 75km of the grounding line or ice shelf edge (whichever is closer). Since we don't have the grounding lines I've just used a crude mask from the ice shelf edge to determine NIS and DIS, so it's not a great comparison. 

Bit hard to tell from these if we're getting closer to obs. E.g. temp spread in western Prydz Bay (WPB) looks better in the heat balance but the salinity spread in the same region looks better in the Gade formulation.  But we are getting the ISW in the Gade formulation which the other simulations do not have!

<img width="947" alt="Screen Shot 2022-11-24 at 4 44 46 pm" src="https://user-images.githubusercontent.com/62230733/203873973-ee53b241-ea58-4656-a64e-a7cdee00d593.png">

<img width="956" alt="Screen Shot 2022-11-24 at 4 52 38 pm" src="https://user-images.githubusercontent.com/62230733/203873581-3037e3c8-2ce3-47ab-a309-14d9d900710d.png">

**Comment by hrsdawson** [comment]
And here's a comparison against CTD data in the Amundsen Sea from [Biddle et al. (2019)](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019JC015133). Looks like an improvement. Still a warm bias for salinities between ~34-34.7 g/kg but improved with respect to heat balance formulation and the temp spread for fresher waters is better. Would be good to plot the Gade line on this as per issue #42.

![Screenshot from 2022-11-25 10-33-37](https://user-images.githubusercontent.com/62230733/203874587-c3167a75-bdd3-48af-a7e4-81d9c007a410.png)

![Slide1](https://user-images.githubusercontent.com/62230733/203874477-110cf176-42d5-42ea-b85e-d41634807401.png)

**Comment by hrsdawson** [comment]
Updated T-S diagrams compared to observations in West Antarctica. 

First two figures show comparison to profiles in front of the Dotson ice shelf (Yang et al., 2022). The Basal + Ice berg run shows a better temperature distribution than the Control and Basal only run, but we are getting a salinity increase for some waters in this simulation which appears further from the obs. Note the different x-axis between the obs figure (left) and model plots (right). 

<div>
<img src="https://user-images.githubusercontent.com/62230733/223934164-61a07f1e-36b4-4f30-997c-02e94f001969.png" width="220"/>
<img src="https://user-images.githubusercontent.com/62230733/223934175-b6cc7187-8764-4b41-8c80-ccd6a598d3ca.png" width="580"/>
</div>

<div>
<img src="https://user-images.githubusercontent.com/62230733/223934620-564cd798-f2a6-46fa-b311-99d0d5dcf911.png" width="220"/>
<img src="https://user-images.githubusercontent.com/62230733/223934631-0ebebb0c-93b6-4e07-a96d-33461fd177c1.png" width="580"/>
</div>


Here's a comparison to profiles from the Amundsen Sea sector (Biddle et al., 2019). These profiles span the summer months (January - March) so I've selected out only these months from the last year of simulation (year 7). Surface waters seem closer to obs in the Basal + Iceberg simulation but, as above, you can see a distinct increase in salinity for waters deeper than ~700 m (these waters are mostly south of ~74S, so close to the ice shelves). Note the different x-axis between the obs on the left and model simulation on the right).  
<div>
<img src="https://user-images.githubusercontent.com/62230733/223935123-6eb526c9-0574-400e-8fca-0a44cb4aed2f.png" width="200"/>
<img src="https://user-images.githubusercontent.com/62230733/223935166-6fbf69d3-cf52-4045-9ed2-28c390aff003.png" width="600"/>
</div>


I've looked at some regional T-S diagrams from other sectors of Antarctica and have not seen this same salinity increase. Any suggestions for digging into this more? Could it be related to more CDW on the shelf?  Would you expect such a change in salinity from this alone?

**Comment by adele157** [comment]
That Amundsen fish tail is really bizarre. I don't think it's just more CDW, because the warm/salty peak that was already there is the CDW and this new salty water is way saltier than that.  Maybe we're forming dense water there now and it's mixing with warm CDW to produce these warm/salty waters? 

@claireyung maybe looking at the salt budget in this region would help? See if there's a lot more brine rejection going on?

**Comment by claireyung** [comment]
Freshwater fluxes in Amundsen region in kg/s/m^2 of FW

Difference between Iceberg and Basal experiments for year 2155
![image](https://user-images.githubusercontent.com/61528379/225825029-e12e4825-ac2f-474b-88a2-f3192fb49823.png)

Total Iceberg Run fluxes for year 2155
![image](https://user-images.githubusercontent.com/61528379/225824482-bddb476e-4504-4856-81e6-314bdc6e4337.png)

Looks like the restoring anomaly is taking away FW, so adding salt in this region compared to no icebergs? (Am I interpreting this correctly?)

**Comment by adele157** [comment]
Yes I think that's right. When the sea ice melts in the 63-67S latitude band it freshens the surface, and the restoring tries to counteract that by add salt. But that's out in the open ocean, not on the shelf. And at the surface, not at depth, so I'm not sure that could be responsible for the fishtail thing.

Perhaps some transects across the shelf/slope would be useful to see where the high salinity is coming from? I'm pretty sure that's saltier than off-shore CDW, but a transect would show that clearly.

**Comment by pedrocol** [comment]
![comp_obc_surf](https://user-images.githubusercontent.com/23285319/226231134-046052a8-2798-4461-a8da-11e7974e5884.png)

The bias observed in the open ocean seams to be coming mostly from the salinity restore

**Comment by hrsdawson** [comment]
This morning we discussed the unusual Amundsen Sea 'fishtail' in the iceberg run and looked at several transects of salinity. The first figure is a longitudinal transect running along the shelf at 74S in front of the major ice shelves . The second is an across-shelf transect at 106W. The high salinity water at depths >600m is clearly visible. This is probably not due to CDW accessing the shelf since the salinities are higher than in the offshore reservoir of CDW water. 

There were several suggestions for further investigation (see next post for figures):
1. How is it changing over time (plot a time series of salinity). 
2. Are we triggering deep convection that is leading to this high salinity water (look at maximum mixed layer depths)? 
3. What does the bathymetry look like in this region? Is water pooling in troughs and unable to escape?

![Screenshot from 2023-03-23 14-21-51](https://user-images.githubusercontent.com/62230733/227093998-19383d6a-eb23-49df-a7be-915590eb2db0.png)
![Screenshot from 2023-03-23 14-21-43](https://user-images.githubusercontent.com/62230733/227094030-1b1c7d81-0e8c-481b-87d0-5b7c9b18046d.png)

**Comment by hrsdawson** [comment]
**1) Salinity time series.** Overall the Amundsen Sea continental shelf is freshening in the basal and ice berg runs but if we look below 600m only the iceberg run has a strong increase in salinity over time. This time series is capped at year 10 because I'm having trouble accessing the later years. 

![Screenshot from 2023-03-23 14-32-11](https://user-images.githubusercontent.com/62230733/227095346-ab04b663-3b7d-45d9-99fa-83cf5012c752.png)

![Screenshot from 2023-03-23 14-32-17](https://user-images.githubusercontent.com/62230733/227095396-98df465e-3da5-45d4-b0d2-db32d9a66048.png)

**Comment by hrsdawson** [comment]
**2) MLD depths.** Maximum mixed layer depths are much greater in the iceberg run than the control, so it looks like we might be triggering deep convection. However, there are some years in the basal only simulation that also have large maximum mixed layer depths without the same salinity increase. Perhaps it's to do with the total area over which we get deep mixed layers, or the specific locations of the deep mixed layers. The second figure shows MLDs cross the region in Jul, Aug, and Sep. We get deeper mixed layers along the ice shelf fronts in the southern Amundsen Sea (in particular Crosson and Thwaites) in the ice berg run. 

![Screenshot from 2023-03-23 14-35-17](https://user-images.githubusercontent.com/62230733/227095609-ef95ef94-ad72-47a1-9ac3-5ddd15c86951.png)

![Screenshot from 2023-03-23 14-38-26](https://user-images.githubusercontent.com/62230733/227096009-f92fdbb9-d827-4f69-97f7-31334b851cef.png)

**Comment by hrsdawson** [comment]
**3) Bathymetry.** @aekiss you might be right, there are some deep pockets on the shelf that could prevent the high salinity water from draining. Still curious that this is not an issue in the basal only run in which we still (sometimes) get deep mixed layers... The red line shows the location of the longitudinal transect from a few posts above. 

![Screenshot from 2023-03-23 14-43-59](https://user-images.githubusercontent.com/62230733/227097539-4127866d-6e3a-406b-9abf-8c4cb5014ec7.png)

**Comment by adele157** [comment]
Closing this issue because it uses the old simulations. See new T/S diagrams issue https://github.com/pedrocol/basal_mom5-collaborative-project/issues/62.
