### ISSUE TITLE
What scheme does NEMO (Mathiot et al. 2017) use?

### ISSUE THREAD

**Issue by adele157** [pedrocol/basal_mom5-collaborative-project#59]
They say they have a z* model and input freshwater at depth. How do they do this? Do they have zero salt flux in the scheme?

**Comment by pedrocol** [comment]
It looks like the NEMO code went through the same considerations as we did. In the NEMO book you can find the explanation below, a flag was used in order to choose how to affect the salinity (absolute salinity is the prognostic variable used in NEMO), with the divergence or with a salinity flux.
![Screenshot from 2023-04-09 18-51-15](https://user-images.githubusercontent.com/23285319/230798174-dc527827-0b5e-441f-b518-594d0ec8b2a2.png)

The current version of the code no longer has this flag, and they only affect the salinity with divergence. They work in the following way:

1) Negative heat flux plus a correction term for the freezing point temperature (line 155 sbcisf.F90)
![Screenshot from 2023-04-09 19-07-23](https://user-images.githubusercontent.com/23285319/230798782-ac06182c-4ed6-497e-8052-c13400366cba.png)

My guess is that it it assumed that the insertion is done in T_insitu<0, and therefore there is a positive heat flux coming from melted water (correction term).

2) Distribution at depth 

Even distribution at depth (lines 176 to 192 sbcisf.F90)

3) Volume flux passed to divergence array

The subroutine "sbc_isf_div" (sbcisf.F90) is called in line 103 of divhor.F90, to update the horizontal divergence with the runoff inflow (3d insertion).

**ssh affects divergence: ssh increment with z_star is incorporated via a correction of the local divergence across all the water column

4) Divergence conservation

Since the divergence is conserved (Incompressibility hypotheses), the three dimensional divergence of the velocity vector is assumed to be zero. Therefore a source in the divergence array, will affect the velocity field. It is less clear to me how this could lead to a decrease in salinity at depth in a z_star context, both conceptually and in the code.
Steve explains this well in https://github.com/pedrocol/basal_mom5-collaborative-project/issues/36#issuecomment-1499677359, but I'm still trying to understand it so I can change the code

**Comment by StephenGriffies** [comment]
MOM5 has the mas_source contribution to the velocity divergence coded already.  So all you need to do is focus on the mass_source array for inserting the fresh melt at the k-levels of choice.  Once that is done, MOM5 will handle the velocity calculations, etc., as per my notes.  The key thing to do is remove the salt source/sink term.

**Comment by pedrocol** [comment]
The MOM5 code was modified according to Steve's comment, the salt budget problem was solved, no longer need this issue
