### ISSUE TITLE
Temp / salt comparison with observations

### ISSUE THREAD

**Issue by adele-morrison** [pedrocol/basal_mom5-collaborative-project#63]
Compare against the [Pathenet et al. 2021 climatology](https://zenodo.org/record/4071906#.YwWmKJNBxqs) for upper ocean temp/salt, and against Schmidtko et al. 2014 for bottom shelf temperature.

Previous issue using old simulations is https://github.com/pedrocol/basal_mom5-collaborative-project/issues/37.

**Comment by adele157** [comment]
Bottom temperature averaged over year 10, comparison to the Schmidtko data:
 <img width="987" alt="Screenshot 2023-08-10 at 10 15 02 am" src="https://github.com/pedrocol/basal_mom5-collaborative-project/assets/8506963/311b682a-ae2d-4176-9ddc-2286db1158e1">

I would say it's hard to tell if the basal and ice berg runs are any better than the control? Amundsen definitely gets even more biased cold compared to obs.

**Comment by adele157** [comment]
And here's the salinity anomaly in year 10 compared to Schmidtko:
<img width="1714" alt="Screenshot 2023-08-10 at 10 20 57 am" src="https://github.com/pedrocol/basal_mom5-collaborative-project/assets/8506963/fb0f0528-93cf-4c61-b858-02f00b4a63e8">

Looks like we have some improvement there. The control is too fresh compared with obs, and this bias improves somewhat in the basal and again in the iceberg run.

**Comment by adele157** [comment]
Comparison of the model temp and salt in the upper 50m in year 10 (a 1 yr avg) with the Pauthenet et al. 2021 obs:
<img width="1442" alt="Screenshot 2023-08-10 at 10 49 09 am" src="https://github.com/pedrocol/basal_mom5-collaborative-project/assets/8506963/1105a3b2-74ed-452d-85d2-02b3b1d0ee64">

* The very fresh bias along the coast in the control is improved.
* Mostly the rest looks similar.
* Perhaps the surface of the Weddell shelf looks to be getting too salty in the iceberg run.

**Comment by adele157** [comment]
Same as above (year 10 in the model compared to Pauthenet), but now for mid-depth: 300-350m.

<img width="1390" alt="Screenshot 2023-08-10 at 10 53 40 am" src="https://github.com/pedrocol/basal_mom5-collaborative-project/assets/8506963/ea92a3fc-90ac-421e-9e6d-064def40a4b1">

* This shows the same cold bias appearing in West Antarctica as we saw in the bottom temp Schmidtko plot above. The control temperature looks arguably looks better in West Antarctica than the basal or iceberg runs. The temperature biases around the rest of Antarctica look pretty similar in the control and basal/iceberg runs.
* Salinity at mid-depth seems to get worse in the basal and ice berg runs compared to the control (particularly the Weddell and Ross regions get too salty). This is at odds with what we saw in the bottom Schmidtko salinity comparison above, where the Weddell and Ross fresh biases improve. I guess because the biases change sign with depth, and we're improving the bottom shelf waters, but not the mid-depth shelf waters.

**Comment by adele-morrison** [comment]
As well as the above plots comparing with obs, it would also be useful to plot temperature and salinity difference maps of Basal minus Control, and ICB minus Control. Given the large biases in the plots compared to obs, it's hard to see from the above plots what the smaller differences between the experiments are.

**Comment by hrsdawson** [comment]
Here's the figures above updated to include the new simulation (Basal-NoGade). Out of the three simulations, the biases in Basal-NoGade look most similar to the control. 

Near the surface (10-50m):

- The fresh bias along the coast is slightly improved in Basal-NoGade compared to the control, but not to the same extent as the two Basal Gade simulations. 
- The salty bias in the Ross Sea is slightly improved in Basal-NoGade. 
<img width="1347" alt="Screenshot 2023-11-02 at 3 36 55 pm" src="https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/99cd4fc0-fbde-492a-b7dd-4b29c7be4f98">



At mid-depth:
- Salinity biases in the Ross Sea are reduced in Basal-NoGade. 
<img width="1346" alt="Screenshot 2023-11-02 at 3 38 54 pm" src="https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/3ac3df7a-f1ba-425b-893d-64eef9edd260">

**Comment by hrsdawson** [comment]
> As well as the above plots comparing with obs, it would also be useful to plot temperature and salinity difference maps of Basal minus Control, and ICB minus Control. Given the large biases in the plots compared to obs, it's hard to see from the above plots what the smaller differences between the experiments are.

Here are the temperature and salinity differences in the three simulations compared to the control at;

**Near surface (10-50m)**:
<img width="1281" alt="Screenshot 2023-11-02 at 3 41 44 pm" src="https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/07ff30e8-ec4d-43a6-8f53-63da7e346814">

- Temperature differences are small around the shelf but show opposite responses in the Gade vs No Gade simulations. The two Gade simulations show cooling in the Amundsen and warming in the Ross Sea compared to the control. The Basal - No Gade simulation shows warming in the Amundsen and slight cooling in the Ross Sea. 
- All three simulations show increase in coastal salinity compared to the control, which acts to improve the coastal fresh bias when compared with obs.  This is most pronounced in the Basal+ICB Gade simulation and least pronounced in the Basal - No Gade simulation. 
- The Basal - No Gade simulation also shows a slight freshening in the Ross Sea (which takes it slightly closer to observations) while the two Basal Gade simulations conversely show slight increase. 

And **mid-depth (300-350m)**:
<img width="1286" alt="Screenshot 2023-11-02 at 3 42 16 pm" src="https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/719a32a2-1fde-4558-aca0-f8cad13810bc">

**Comment by hrsdawson** [comment]
> And here's the salinity anomaly in year 10 compared to Schmidtko: <img alt="Screenshot 2023-08-10 at 10 20 57 am" width="1714" src="https://private-user-images.githubusercontent.com/8506963/259581898-fb0f0528-93cf-4c61-b858-02f00b4a63e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2OTQ0NzEsIm5iZiI6MTcwNzY5NDE3MSwicGF0aCI6Ii84NTA2OTYzLzI1OTU4MTg5OC1mYjBmMDUyOC05M2NmLTRjNjEtYjg1OC0wMmYwMGI0YTYzZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTFUMjMyOTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTU4ODc1ZGMwYjY2NGUyZmU4YmYxODNmNjE1NWNlYzNjYTJjMDRkMmJmNjZmMGNlYjhjYTlhNmQzZmI4ZDMzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UXYGZXwBznTplEeZ8zziO41PlwpSljStpFvz6bHxD0U">
> 
> Looks like we have some improvement there. The control is too fresh compared with obs, and this bias improves somewhat in the basal and again in the iceberg run.

I've been updating Figure 4 (comparison of bottom T-S to observations) and noticed I'm not seeing the same on-shelf bottom freshening in the experiments compared to Schmidtko as shown in this figure. I think this might be because the figure above used the models practical salinity, not absolute salinity when comparing to obs (that's the only way I can replicate the freshening). If I'm right about this, the control is only really too fresh in the Weddell , eastern Ross Sea and eastern Prydz Bay (see below showing bottom salinity in all experiments compared to Schmitdko).  We improve the Weddell Sea bias in the Gade + ICB simulation (except maybe that southeast patch), but we make it worse in the Ross Sea , parts of the Amundsen and along the AP.

<img width="554" alt="Screenshot 2024-02-12 at 10 35 22 am" src="https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/76942a96-c182-47e1-97a8-7e6a9745ecd6">

**Comment by hrsdawson** [comment]
Here's the full updated figure. Observations are Schmidtko on the shelf and WOA18 in the abyss. Control is compared to these obs and the $Basal_{gade}$ and $Basal_{gade}$ + ICB experiments are compared to the  control. 

Note: There's some odd artefacts in the WOA18 salinity field close to the shelf which I think results from interpolation onto the model grid, though they don't show up in the temperature fields. We could use WOA13 obs which don't have this artefact and show basically the same abyssal biases in the control. Or, if we want to stick with WOA18 I could try improving the interpolation (it's pretty rudimentary currently). 

![Figure04_T-S_obs_bottom_comparison_woa18](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/059db5b0-96f8-4fd5-85c1-9568fa2d14af)


For reference, this is the WOA13 obs in the abyss. 
<img width="1126" alt="Screenshot 2024-02-12 at 10 53 56 am" src="https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/32960ea9-0f85-4554-8462-5b252e54067b">

**Comment by aekiss** [comment]
see plots from new experiments: https://github.com/pedrocol/basal_mom5-collaborative-project/issues/84
